# Generated by Django 4.2.7 on 2024-03-02 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderupdate_id', models.IntegerField(default=0)),
                ('items', models.TextField(default='')),
                ('mymessage', models.CharField(default='The Order Has Been Placed Sucessfully', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ordercontact', models.CharField(default='9965479094', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
