# Generated by Django 4.2.7 on 2024-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('remarks', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('phone', models.CharField(max_length=111)),
                ('date', models.CharField(max_length=111)),
                ('time', models.CharField(max_length=111)),
                ('timed', models.CharField(max_length=111)),
                ('guests', models.CharField(max_length=111)),
            ],
        ),
    ]
