# Generated by Django 4.2.7 on 2024-03-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingupdate_id', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=111)),
                ('name', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=111)),
                ('time', models.CharField(max_length=111)),
                ('timed', models.CharField(max_length=111)),
                ('guests', models.CharField(max_length=111)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
