# Generated by Django 4.2.7 on 2024-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_bookingupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discountprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingupdate',
            name='remarks',
            field=models.CharField(default='pending', max_length=111),
        ),
    ]
