# Generated by Django 4.2.7 on 2024-03-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_blogpost_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
