# Generated by Django 4.2.7 on 2024-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_blogpost_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
