# Generated by Django 4.2.7 on 2024-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
