# Generated by Django 4.2.7 on 2024-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_blogpost_like_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(default='/media/app1/imagesloginimage1.jpg', upload_to='app1/images'),
        ),
    ]
