# Generated by Django 4.2.7 on 2024-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_comment_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='User@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Laughtale', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
